heat_template_version: 2013-05-23

description: Template para la creación de un volumen a partir de una imagen


resources:
  the_resource:
    type: OS::Cinder::Volume
    properties:
      availability_zone: nova
      # backup_id: String
      # description: String
      image: Debian Jessie (stable)
      # metadata: {...}
      name: volume_debian
      # read_only: Boolean Available since Liberty
      # scheduler_hints: {...}
      size: 2
      # snapshot_id: String
      # source_volid: String
      # volume_type: String
      # imageRef: 
