heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance and install a package

parameters:
  image:
    type: string
    description: Image ID or image name to use for the server4
    default: Debian Jessie (stable)
    constraints:
      - allowed_values: 
        - Debian Jessie (stable)
        - Fedora 20
  flavor:
    type: string
    description: Sabor de la instancia
    default: m1.small
    constraints:
      - allowed_values: [m1.small, m1.medium]
        description: InstanceType must be one of m1.small, m1.medium or m1.large
  key_name:
    type: string
    default: clave_ale
    description: Clave SSH
  paquete:
    type: string
    default: ansible

resources:
  Instancia_de_prueba:
    type: OS::Nova::Server
    properties:
      name: Debian
      key_name: {get_param: key_name}
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks: [{"network":"red de alejandro.nieto"}]
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y aptitude package
          params:
            package: { get_param: paquete}