heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameters:
  image:
    type: string
    description: Image ID or image name to use for the server4
    default: Debian Jessie (stable)
    constraints:
      - allowed_values: 
        - Debian Jessie (stable)
        - Fedora 20
  flavor:
    type: string
    description: Sabor de la instancia
    default: m1.small
    constraints:
      - allowed_values: [m1.small, m1.medium]
        description: InstanceType must be one of m1.small, m1.medium or m1.large

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: clave_ale
      image: { get_param: image }
      # ImageId: { get_param: ImageId }
      flavor: {get_param: flavor}
      networks: [{"network":"red de alejandro.nieto"}]



