heat_template_version: 2013-05-23

description: plantilla simple para establecer la contrasenna de administrador para una maquina virtual

parameters:
  key_name:
    type: string
    label: Key Name
    description: Nombre del par de claves a utilizar para la instancia
  image_name:
    type: string
    label: Image Name
    description: Nombre de la imagen a utilizar para la instancia
  password:
    type: string
    label: password
    description: admin password
    hidden: true


resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      admin_user: sampleuser
      image: { get_param: image_name }
      flavor: m1.small
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo "Setting  password to  " $password           
            echo $password |passwd --stdin sampleuser

          params:
            $password: { get_param: password }